all: socket pipe mpq

socket: question_2_p1_socket.c question_2_p2_socket.c
	gcc -o q2_socket question_2_p1_socket.c
	gcc -o p2_socket question_2_p2_socket.c

pipe: question_2_p1_pipe.c question_2_p2_pipe.c
	gcc -o q2_pipe question_2_p1_pipe.c
	gcc -o p2_pipe question_2_p2_pipe.c

mpq: question_2_p1_mpq.c question_2_p2_mpq.c
	gcc -o q2_mpq question_2_p1_mpq.c
	gcc -o p2_mpq question_2_p2_mpq.c