all: q1 q2a q2b q2cstack q2cqueue q3 q5

q1: question_1.c
	gcc -o q1 question_1.c
q2a: question_2_a.c
	gcc -o q2a question_2_a.c
q2b: question_2_b.c
	gcc -o q2b question_2_b.c
q2cstack: question_2_c_stack.c
	gcc -o q2cstack question_2_c_stack.c
q2cqueue: question_2_c_queue.c
	gcc -o q2cqueue question_2_c_queue.c
q3: question_3.c 
	gcc -o q3 question_3.c -lm
q5: question_5.c
	gcc -o q5 question_5.c